implement-creating-and-exporting-users-using-files
Stan3slaw/Express.js_parody pull request #1
Opened 2022-10-21 09:50 UTC by Stan3slaw

implemented creating users from file and exporting users to file

2022-10-21 13:21 UTC, bohdan-shtohrinets-sigma requested changes

2022-10-21 13:21 UTC, bohdan-shtohrinets-sigma commented on src/users/users.service.js
> +const exportUsersToXml = (_, res, usersInXml, filePath) => {
@Stan3slaw why you ignore firts arg? If it is not needed why you include it here?

2022-10-21 13:21 UTC, bohdan-shtohrinets-sigma commented on src/users/users.service.js
> +
@Stan3slaw better to use classes

2022-10-21 13:21 UTC, bohdan-shtohrinets-sigma commented on src/users/users.controller.js
>  const find = (req, res) => {
@Stan3slaw better to use classes

2022-10-21 13:21 UTC, bohdan-shtohrinets-sigma commented on src/users/users.service.js
> +        res.writeHead(200, {
better to do this logic inside controller, services are usually used for business logic management and controllers for resp forming

2022-10-21 13:24 UTC, Stan3slaw commented on src/users/users.service.js
> +const exportUsersToXml = (_, res, usersInXml, filePath) => {
Okay, I will remove it

2022-10-21 13:28 UTC, Stan3slaw commented on src/users/users.service.js
> +        res.writeHead(200, {
Yeah, I know this stuff, but in this case logic of exporting users to file is strongly bound, so I can't just move this peace of code to the controller.

2022-10-21 13:29 UTC, Stan3slaw commented on src/users/users.controller.js
>  const find = (req, res) => {
Okay, I will fix it.

2022-10-21 13:29 UTC, Stan3slaw commented on src/users/users.service.js
> +
Okay, I will fix it.

2022-10-24 13:15 UTC, bohdan-shtohrinets-sigma approved these changes

2022-10-24 13:15 UTC, bohdan-shtohrinets-sigma commented on src/users/users.service.js
> +        res.writeHead(200, {
@Stan3slaw you can try to save your data to some variable and return it in success case. Otherwise throw error.

2022-10-26 12:00 UTC, merged